### ISSUE TITLE
Rename to en-US spelling

### ISSUE THREAD

**Issue by imagitama** [vrchat-community/LazyOptimiser#2]
_Disclaimer: I am not American and en-US is not my primary language._

This package is named using en-GB spelling however there is an unofficial standard to name packages/tools/scripts with en-US.

It helps people find your packages, it helps devs who are navigating the filesystem (ie finding this repo they cloned) and I think it's good to conform to "standards".

I did a quick Google and found a [debate about it for APIs](https://stackoverflow.com/questions/157807/gb-english-or-us-english).

**Comment by euan142** [comment]
If it were a variable name or such within the code I would be inclined to agree however this is just the name of the tool of which I feel is weird to force a particular spelling. So for now at least the name will remain the current spelling
