### ISSUE TITLE
Invalid merge of mesh

### ISSUE THREAD

**Issue by kibalab** [vrchat-community/LazyOptimiser#6]
**Describe the bug**
Invalid merge of mesh

**Expected behavior**
Improperly merged with models with other armatures

**Logs**
![image](https://user-images.githubusercontent.com/31209389/178795776-5816df4f-b7a7-4ddd-bd70-a50fd3a5bd52.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/31209389/178795730-0d1b1e90-a18a-4fa4-99e5-9df7e84f1e85.png)
![image](https://user-images.githubusercontent.com/31209389/178796225-2f753009-06e2-40c6-8f40-3637d65e7fba.png)

**Additional context**

**Comment by euan142** [comment]
Ah, the new unique key system just goes by gameobject name which can easily (and very likely collide, I'm going to switch it to use the instance id of the transform which will be unique

**Comment by euan142** [comment]
@kibalab I've pushed https://github.com/vrchat-community/LazyOptimiser/commit/396622e06b969a95a8e75153f46211b308609994 it should hopefully fix the issue without needing to group things twice as in https://github.com/vrchat-community/LazyOptimiser/pull/8

**Comment by kibalab** [comment]
I just tried #8 test But it doesn't seem to work out
I tried to print out the log, but ``GetUniqueKey()`` did not generate a key for the Rootbone of the child armature
@euan142

**Comment by euan142** [comment]
I realised the grouping only affected animated meshes when really every mesh should have at least one key, not just to separate by root bone but by various properties. I also went and made the existing generation of unique keys more unique. I pushed the changes in https://github.com/vrchat-community/LazyOptimiser/commit/c20222a030f6860701c3e7870d7f5caad194fa67

**Comment by kibalab** [comment]
Looks like it's working fine now!
